/*
 * Larpcord, a Discord client mod
 * Copyright (c) 2026 Larpcord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// The Larpcord mark: a d20 seen face-on, drawn as ten shaded facets.
// Writes the Android launcher icon layers and the website logo from one geometry.
//   node scripts/larpcord/brand/d20.mjs <android res dir> <site dir>

import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

const [androidRes, siteDir] = process.argv.slice(2);

// 24x24 design space. Outer hexagon, and the front face centred on it.
const cos30 = Math.cos(Math.PI / 6);
const P = {
    top: [12, 2], ur: [12 + 10 * cos30, 7], lr: [12 + 10 * cos30, 17],
    bottom: [12, 22], ll: [12 - 10 * cos30, 17], ul: [12 - 10 * cos30, 7],
    t: [12, 12 - 4.6], bl: [12 - 4.6 * cos30, 12 + 2.3], br: [12 + 4.6 * cos30, 12 + 2.3]
};

// Light comes from the upper left; the front face catches the most.
export const FACETS = [
    [["top", "ul", "t"], "#EBB35A"],
    [["top", "t", "ur"], "#CB8C32"],
    [["ul", "bl", "t"], "#DDA048"],
    [["ur", "t", "br"], "#B47420"],
    [["ul", "ll", "bl"], "#BB7C28"],
    [["ll", "bottom", "bl"], "#99621A"],
    [["bl", "bottom", "br"], "#C28530"],
    [["br", "bottom", "lr"], "#865414"],
    [["ur", "br", "lr"], "#774A11"],
    [["t", "bl", "br"], "#F6CD7C"],
];

const r = n => Math.round(n * 1000) / 1000;
const pathOf = names => "M" + names.map(n => P[n].map(r).join(",")).join(" L") + " Z";
const EDGES = "M" + ["top", "ur", "lr", "bottom", "ll", "ul"].map(n => P[n].map(r).join(",")).join(" L") + " Z " +
    [["top", "t"], ["ul", "t"], ["ur", "t"], ["ul", "bl"], ["ll", "bl"], ["bottom", "bl"], ["ur", "br"], ["lr", "br"], ["bottom", "br"], ["t", "bl"], ["bl", "br"], ["br", "t"]]
        .map(([a, b]) => `M${P[a].map(r).join(",")} L${P[b].map(r).join(",")}`).join(" ");

export function svg({ size = 24, stroke = "#2A1A07" } = {}) {
    const facets = FACETS.map(([names, color]) => `<path d="${pathOf(names)}" fill="${color}"/>`).join("");
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${size}" height="${size}">${facets}` +
        `<path d="${EDGES}" fill="none" stroke="${stroke}" stroke-width="0.35" stroke-linejoin="round" stroke-linecap="round" opacity="0.55"/></svg>`;
}

// Adaptive icons are 108dp with the logo kept inside the central ~66dp safe zone.
function androidVector(body) {
    return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by larpcord/scripts/larpcord/brand/d20.mjs -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <group android:translateX="26.4" android:translateY="26.4" android:scaleX="2.3" android:scaleY="2.3">
${body}
    </group>
</vector>
`;
}

if (androidRes) {
    const facets = FACETS.map(([names, color]) =>
        `        <path android:fillColor="${color}" android:pathData="${pathOf(names)}" />`).join("\n");
    const edges = `        <path android:strokeColor="#8C2A1A07" android:strokeWidth="0.35" android:strokeLineJoin="round" android:strokeLineCap="round" android:pathData="${EDGES}" />`;
    mkdirSync(join(androidRes, "drawable"), { recursive: true });
    writeFileSync(join(androidRes, "drawable", "ic_launcher_foreground.xml"), androidVector(facets + "\n" + edges));
    const mono = `        <path android:strokeColor="#FFFFFFFF" android:strokeWidth="1.1" android:strokeLineJoin="round" android:strokeLineCap="round" android:pathData="${EDGES}" />`;
    writeFileSync(join(androidRes, "drawable", "ic_launcher_monochrome.xml"), androidVector(mono));
    console.log("wrote Android icon layers");
}

if (siteDir) {
    mkdirSync(siteDir, { recursive: true });
    writeFileSync(join(siteDir, "d20.svg"), svg({ size: 64 }));
    console.log("wrote site logo");
}
